name: Publish release on tag creation

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: HAMLET
          use-mamba: true

      - name: Get shortened version of release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check release version is set correctly in every file
        run: python3 utilities/check-version.py ${{ env.RELEASE_VERSION }}

      - name: Run release tests in conda environment
        run: >-
          pytest --keep-workflow-wd-on-fail
          --tag release

  run_tests:
    uses: ./.github/workflows/ci.yml
    needs:
      - release_checks

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: HAMLET
          use-mamba: true

      - name: Get shortened version of release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install LaTeX
        run: sudo apt install -y latexmk texlive-latex-base

      - name: Build the documentation
        run: make --directory docs latexpdf

      - name: Rename documentation
        run: mv docs/build/latex/hamlet.pdf HAMLET-${{ env.RELEASE_VERSION }}.pdf

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: HAMLET-${{ env.RELEASE_VERSION }}.pdf
          retention-days: 1

  package:
    name: Package source files
    runs-on: ubuntu-latest
    needs:
      - release_checks
      - run_tests
      - documentation

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get shortened version of release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Package source code
        shell: bash
        run: |
          find * | grep -v "\.git\|pytest.ini" | tar -czvf HAMLET-${{ env.RELEASE_VERSION }}.tar.gz --files-from -

      - name: Print event context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

      - name: Upload archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-tar
          path: HAMLET-${{ env.RELEASE_VERSION }}.tar.gz
          retention-days: 1

  release:
      name: Create release
      needs:
        - release_checks
        - run_tests
        - package
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Get shortened version of release tag
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        - name: Download release tarball
          uses: actions/download-artifact@v4
          with:
            name:
              - release-tar
              - documentation

        - name: Create release
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh release create \
              ${{ env.RELEASE_VERSION}} \
              --generate-notes \
              HAMLET-${{ env.RELEASE_VERSION }}.tar.gz \
              HAMLET-${{ env.RELEASE_VERSION }}.pdf
